name: build and deploy to gh-pages

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: get pip cache
      id: pip-cache
      run: |
        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"
    - name: cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashfiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Install dev-dependencies
      run: pip install -r requirements.txt -r requirements-dev.txt
    - name: Install jo
      run: |
        curl -LO https://github.com/jpmens/jo/releases/download/1.4/jo-1.4.tar.gz
        tar xfz jo-1.4.tar.gz
        cd jo-1.4 && ./configure && make && sudo make install
    - name: coverage test
      run: nosetests -c .noserc
    - name: build wheel
      run: python setup.py bdist_wheel
    - name: install sphinx
      run: pip install sphinx
    - name: build sphinx dir
      run: sphinx-apidoc -F -o docs revjo
    - name: make apidoc
      run: make PYTHONPATH=.. -C docs html
    - name: make output dir
      run: mkdir output/
    - name: copy docs
      run: cp -r docs/_build/html/* output/
    - name: copy coverage report
      run: |
        cp -r cover/ output/coverage/
        cp coverage.xml output/coverage/
    - name: disable jekyll
      run: touch output/.nojekyll
    #- name: create index
    #  run: dir2pi -S dist
    #- name: merge contents
    #  run: cp -r dist/simple/ cover/dist/
    - name: deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./output
      with:
        forceOrphan: true
